### ISSUE TITLE
System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by ghost** [soupstream/InfiniteVariantTool#2]
Here's the full error report. I do not understand what it means but from what I can tell it's something related to failure to retrieve game cache.
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at InfiniteVariantTool.Core.Cache.OfflineCacheManager.get_GameManifestUrl()
   at InfiniteVariantTool.Core.Cache.OfflineCacheManager.get_GameManifestPath()
   at InfiniteVariantTool.Core.Cache.CacheManagerBase.LoadGameManifest()
   at InfiniteVariantTool.Core.VariantManager.LoadCache(String language)
   at InfiniteVariantTool.GUI.AllVariantsViewModelContext.<>c__DisplayClass1_0.<LoadVariantsBase>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at InfiniteVariantTool.GUI.AllVariantsViewModelContext.LoadVariantsBase(VariantManager variantManager)
   at InfiniteVariantTool.GUI.VariantViewModelContext.LoadVariants(VariantManager variantManager)
   at InfiniteVariantTool.GUI.VariantViewModel.LoadVariants()
   at InfiniteVariantTool.GUI.VariantViewModel.<get_LoadVariantsCommand>b__14_0(Object _)
   at InfiniteVariantTool.GUI.AsyncRelayCommand.ExecuteAsync(Object parameter)
   at InfiniteVariantTool.GUI.AsyncRelayCommand.Execute(Object parameter)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by soupstream** [comment]
Finally fixed this in v0.2.0
