### ISSUE TITLE
Extract Engine Variant fails with 404

### ISSUE THREAD

**Issue by 2Tie** [soupstream/InfiniteVariantTool#3]
Tried extracting a few gametypes (Arena:Slayer, Fiesta:FFA Slayer, Event:Escalation Slayer) to get to grips with the tool (hoping to script my own mode at some point), but whenever "also extract engine game variant" is checked, i get the following:

Error

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at InfiniteVariantTool.Core.Cache.CacheManager.DownloadFile(ApiCall apiCall, MimeType mimeType)
   at InfiniteVariantTool.Core.Cache.CacheManager.GetFile(ApiCall apiCall, MimeType mimeType)
   at InfiniteVariantTool.Core.VariantManager.GetVariant(Guid assetId, Guid versionId, VariantType type, Boolean getFiles, Boolean getLinkedVariant)
   at InfiniteVariantTool.Core.VariantManager.GetVariant(Guid assetId, Guid versionId, VariantType type, Boolean getFiles, Boolean getLinkedVariant)
   at InfiniteVariantTool.GUI.ExtractViewModel.ExtractVariant()
   
without it checked, the tool succeeds (generates a UcgGameVariant.json file and populates an images folder for the variant's folder).

I've noticed that no Engine Game Variants appear in the All Variants tab (with View->EGV checked), though i'm not sure if they're supposed to.

**Comment by soupstream** [comment]
Thanks for letting me know, I've fixed this in the latest version.
